select * from utr_register;

drop table utr_register;

create table if not exists UTR_REGISTER (ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100), REF VARCHAR(10),CONSTRAINT REF_CONST UNIQUE (REF));